### ISSUE TITLE
Any way to catch/transform `jest.mock(<library>)` calls?

### ISSUE THREAD

**Issue by jnardone** [LeDDGroup/typescript-transform-paths#100]
In Jest, you can mock an entire module with something like

`jest.mock('../../path/to/code');`

However, unlike my import statements, the transformer here doesn't recognize these nor transform them.

It would be really great if it did.  Then I wouldn't have to separately manipulate paths via Jest's aliases and just use the transpiled code everywhere; I can trigger this transformation as part of ts-jest/ttypsecript and it works for all my module resolution except this case.

Is there a way to support this?  Does it already?

**Comment by nonara** [comment]
Great suggestion. I will implement this with an option to enable in plugin config. Until the next major version, the option will be false, by default.

I'll let you know when it's added.

**Comment by nonara** [comment]
In thinking this through a bit more, I recognize that this goes a bit beyond the scope of what we're doing. I had forgotten that jest maintains its own separate path aliases configuration. As a result, it would complicate things and give rise to many different issues being reported from people who expected it to work in certain ways (ie. when being run with ts-node, working with jest's aliases, etc)

I apologize for my hasty confirmation on this. However, for the reasons stated, we won't be able to implement this request. I suggest continuing to use jest's aliases, as this is what they were intended for.

To make matters easier, you can synchronize your aliases with tsconfig via: https://github.com/sebastianmusial/jest-module-name-mapper
