### ISSUE TITLE
v2.2.4 can't resolve default pathname with index.js like v2.2.3 can

### ISSUE THREAD

**Issue by viT-1** [LeDDGroup/typescript-transform-paths#106]
[My repo](https://github.com/viT-1/systemjs-ts-es6-vue/tree/018cfb5c50a936521d3438cf940b064666eafadb) for testing case
with `npm run deploy.dev` v2.2.3 resolves imports in `dist/main.js` as
`import { GreeterUse } from "./common.blocks/GreeterUse/index.js";`
but v2.2.4 as
`import { GreeterUse } from "./common.blocks/GreeterUse.js";`

**Comment by nonara** [comment]
Thanks for the report, and sorry about the issue!

Please give v3.0 a try and let me know if you have any issues.
