### ISSUE TITLE
V3 doesn't rewrite imports

### ISSUE THREAD

**Issue by mikearnaldi** [LeDDGroup/typescript-transform-paths#114]
when upgrading to v3 in https://github.com/Effect-TS/core I noticed modules are no longer replaced, we use typescript-transform-paths for our test suite and all the tests were failing for "module not found".

debugging manually shows the following:

V3:

![V3-BUG](https://user-images.githubusercontent.com/24249610/123137769-3cf19380-d44c-11eb-87f7-0a1a1bfc2505.png)

V2:

![V2-OK](https://user-images.githubusercontent.com/24249610/123137793-467afb80-d44c-11eb-834c-611f3dce7c71.png)

A quick repro can be done by cloning the repo in question using a tsconfig like:

```json
{
  "extends": "./tsconfig.json",
  "files": [],
  "compilerOptions": {
    "target": "ES2018",
    "module": "CommonJS",
    "plugins": [{ "transform": "typescript-transform-paths" }],
    "outDir": "debug"
  },
  "include": ["scripts/jest-setup-after-env.ts"]
}
```

when used with v2 the import `@effect-ts/system/Structural` of `scripts/jest-setup-after-env.ts` is replaced with v3 is left untouched

**Comment by nonara** [comment]
Interesting! Looks like it may be connected to extended config files. Having a look into this now

**Comment by nonara** [comment]
So this is related to a breaking change in the `matchPatternOrExact` function. More specifically, it looks like they added caching to the paths pattern parsing to speed things up.

Relevant commit: https://github.com/microsoft/TypeScript/commit/3ffa245f07c4472ed3015fcb59ea0d2d73432102

I'm hesitant to fix this now, as this is only in dev builds and is not in an official release yet. But, I see that it's affecting several of you, so I will integrate what's there. Please keep an eye on it, and let me know if things break again.
