### ISSUE TITLE
Performance is slow in at least TS 4.3

### ISSUE THREAD

**Issue by dko-slapdash** [LeDDGroup/typescript-transform-paths#115]
Hi.

The configuration looks like this:

![image](https://user-images.githubusercontent.com/46383452/123582337-77cc3200-d792-11eb-9816-84bf6a0d4051.png)

The number of *.ts files is:

```
# find src | grep .ts | wc -l
1613

# yarn tsc --version
Version 4.3.4
```

- without the plugin: 
    ```
    # yarn ts-patch install
    # rm -rf dist; time yarn tsc
    ✨  Done in 36.60s.
    ```

- with the plugin:
    ```
    # yarn ts-patch install
    # rm -rf dist; time yarn tsc
    ✨  Done in 185.59s.
    ```

As well as typescript-transform-paths v3.0.0, this also applies to v1.1.15 BTW (the compilation takes 144.50s) - it slows the compilation down significantly.

I think there is a O(n^2) computation somewhere in the code of the plugin, because on an even large codebase, it runs just forever.

**Comment by nonara** [comment]
Does the issue apply to v2 of the plugin as well?

Also, is this specific to TS v4.3 or does it apply with older versions also?

**Comment by nonara** [comment]
@dko-slapdash Please provide a repo with a single project containing 1000+ source files, and I'll do some perf investigation

**Comment by dko-slapdash** [comment]
The repo we're working on is proprietary, so I can't share it unfortunately.

**Comment by nonara** [comment]
Got it. The code on our side is pretty well optimized for performance. If you're seeing the same result with v1, then I'm especially inclined to believe that it's just general transformer/visitor lag or something in the API calls.

The reason for this is the code from v1 to v2-3 is entirely rewritten and uses different logic, entirely.

But I'd still like to have a look. I'm incredibly swamped, though, so if you can track out a repo of reasonable size, let me know, and I'll take a look.

*Does the same delay happen with v2?*

Another possibility is if you have a large amount of paths patterns. The latest dev build of TS gives that issue by introducing caching. V3 already supports that, so you might give that a try.

**Comment by nonara** [comment]
@dko-slapdash I might have come across what you're describing. In your large project structure, were you using project references?

It looks like TS is triggering transformations for non-emitted referenced files, which could get pretty bogged down quite quickly.

**Comment by dko-slapdash** [comment]
Yes, we're using project references.  But at the same time, in the above example in the issue description, `tsc` is run without `-b` switch, which means that it builds the current project indendently.

**Comment by nonara** [comment]
Ah, yes, Didn't notice that. Thanks for the response. I'll see about building a large repro before the next release to see if 
I can reproduce and if so, to isolate where the lag is coming from.
