### ISSUE TITLE
can't surpport Module Augmentation feature

### ISSUE THREAD

**Issue by hans000** [LeDDGroup/typescript-transform-paths#122]
[Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation)

for example
```
// ./typing.ts
declare module '~/lib/core' {
    interface Foo {
        foo(msg: string): void;
    }
}
// output
// ./dist/typing.d.ts
declare module '~/lib/core' {
    interface Foo {
        foo(msg: string): void;
    }
}
```

**Comment by nonara** [comment]
Great suggestion! I didn't realize that these were resolved in the same way as imports / exports.

Shouldn't be hard to implement. Added to my queue.

**Comment by nonara** [comment]
Added in v3.1.0.
