### ISSUE TITLE
Feature: Support ts-node transpileOnly

### ISSUE THREAD

**Issue by jasonkuhrt** [LeDDGroup/typescript-transform-paths#123]
This issue is a port from https://github.com/cevek/ttypescript/issues/123#issuecomment-879443563.

## Maintainer's Note

The request is to support the transformer without needing a `Program` / `EmitHost`. Investigation needs to be done to see if this is feasible.

**Comment by nonara** [comment]
Quick update - hoping to look at this this coming weekend.

**Comment by nonara** [comment]
Added in v3.2.0

**Comment by nonara** [comment]
I recognize that the steps could be easier, so I'm going to add a register script to simplify it.

Ultimately, it should be able to work with: `node -r typescript-transform-paths/register`.

Check back after next weekend

**Comment by jasonkuhrt** [comment]
Seems to be working! But my IDE doesn't see the package as importable right now 🤔 

<img width="931" alt="CleanShot 2021-08-09 at 10 21 34@2x" src="https://user-images.githubusercontent.com/284476/128721988-5c0ae447-4e3b-4814-b4eb-eea99ae15df6.png">

> When I'm done, it should be able to work with: node -r typescript-transform-paths/register.

Sounds good 👍

**Comment by nonara** [comment]
> Seems to be working! But my IDE doesn't see the package as importable right now 🤔

Whoops! Didn't realize we didn't already have the types exported. That should be corrected now.

As for the register script, it's done and ready to go in v3.3.0! Have a look at the latest readme for how-to. Hopefully it's clear and fits people's uses cases. I don't generally use ts-node, but I think we've covered how people want to use it.

**Comment by jasonkuhrt** [comment]
@nonara just fyi its not published on npm yet https://www.npmjs.com/package/typescript-transform-paths

**Comment by nonara** [comment]
@jasonkuhrt GitHub is having some server issues today. Publish action is still sitting in queue after several failures earlier, Just published manually, so it should be available now.
