### ISSUE TITLE
This util doesn't work in this project

### ISSUE THREAD

**Issue by zyf0330** [LeDDGroup/typescript-transform-paths#125]
Hello, I find that this transformer doesn't work in one scene. I create a demo repo https://github.com/zyf0330/transform-paths-demo/tree/main, just follows README.

**Comment by nonara** [comment]
Unfortunately, I'm unable to reproduce that using your project.

Here are the steps I took:

```shell
git clone https://github.com/zyf0330/transform-paths-demo/tree/main
cd transform-paths-demo
npm install
cd packages/b
npm run build
```

This is the compiled result (from index2.js):

```js
exports.src1 = void 0;
// import * as src1 from "../src1/index1"
const src1 = __importStar(require("../../../built/packages/a/src/index1"));
exports.src1 = src1;
console.log('in src2', src1.E);
const _2_1 = require("./2");
console.log('two', _2_1.s);
```

I recommend erasing `node_modules` and reinstalling. Then, check that typescript is patched via `ts-patch check`. 

If it still does not work and you have new steps which can reproduce the problem, please let me know, and I'll have a look.

**Comment by zyf0330** [comment]
`const src1 = __importStar(require("../../../built/packages/a/src/index1"));` shows that src1 is requiring from wrong path. Just run it with node, you can see. 
The correct path is `require('../../a/src/index1.js')`

**Comment by nonara** [comment]
Ah I see. Sorry about that, I thought you meant it didn't transform at all. I will try to take a closer look this weekend.

**Comment by nonara** [comment]
Ok, sorry for the delay on this one. Thanks again for bringing it to my attention!

Turns out the plugin wasn't playing well with project references. The problem happened when the referenced file was outside of the current project. Weird stuff to do with how TypeScript handles resolution paths. Should be sorted out now in `v3.3.1`!
