### ISSUE TITLE
v1.1.2 no longer transforming paths

### ISSUE THREAD

**Issue by sbmw** [LeDDGroup/typescript-transform-paths#13]
Hi, thanks for this excellent plugin.

Unfortunately something seems to have stopped working (for me at least) in v1.1.2.

I've played around with incremental updates and believe the issue is in 73dd832 / "fix: type only import not deleted from result file"

Specifically this change:

![image](https://user-images.githubusercontent.com/30099628/58089001-09e5d180-7bee-11e9-8917-3466f7ff0507.png)

My paths are set as follows:

        "paths": {
            "me/*": ["src/*"]
        },

An import looks like:

    import { FooViewModel } from "me/viewModels/fooViewModel";

For now I can just use 1.1.0.  Please let me know if there's any further info I can provide.

**Comment by anion155** [comment]
Since 1.1.1 this module does not interrupt typescript's logic of module importing. So if you do not use FooViewModel, or if FooViewModel is type and you are waiting for import side effects on runtime. Try to compile your code with original compiler and see if 'me/viewModels/fooViewModel' import is included.

**Comment by anion155** [comment]
For side effect imports usually used:
```ts
import "something";
```

**Comment by anion155** [comment]
@sbmw So, was this the case when you wanted "import side effects" or is this a bug?

**Comment by sbmw** [comment]
@anion155 Thanks for the help, but no I'm not using side effect imports and I believe this is a bug.

I've put together a very basic demo to show this in action: https://github.com/sbmw/transformdemo

One thing I have discovered: I had "module": "esnext" in my tsconfig.  With that set, paths are not transformed in the output .js or .d.ts.  If that is changed to "module": "commonjs" the .js file has its path correctly transformed.  

However, the paths in output .d.ts declaration files are not transformed.  If you were to consume the demo repo above as a package in another project you would get a compilation error like import { ApiResponseViewModel } from "me/viewModels/apiResponseViewModel".

https://github.com/sbmw/transformdemo/blob/master/dist/ajax/fetchHandler.d.ts for reference.

**Comment by anion155** [comment]
About .d.ts read this #4 
Will investigate about "module" configuration. Thanks

**Comment by sbmw** [comment]
Thanks.

Re .d.ts, yes I know that and if you see my tsconfig you'll see I have danielpza's solution in place:

    "plugins": [
      { "transform": "typescript-transform-paths" },
      { "transform": "typescript-transform-paths", "afterDeclarations": true }
    ]

But it is no longer working.

**Comment by anion155** [comment]
Ok, will look into this.

**Comment by danielpza** [comment]
@anion155 , I checked and it do stopped working when we changed from `ts.updateImportDeclaration` to `node.moduleSpecifier.text = file;`

I think we'll have to replicate the way typescript filters declarations as you originally did in #14. Do you still have a previous version of that PR?

**Comment by anion155** [comment]
@danielpza git does not delete anything before `gc` ))

**Comment by danielpza** [comment]
@sbmw the fix is up in v1.1.3, I tested it in your demo https://github.com/sbmw/transformdemo and it worked.
