### ISSUE TITLE
`Error: Cannot find module 'ts-node'`

### ISSUE THREAD

**Issue by osyrisrblx** [LeDDGroup/typescript-transform-paths#130]
Hi,

I got a dependabot PR to update `typescript-transform-paths` for my repository. It looks like it's trying to require `ts-node`, but I do not use that in my project, I use ttypescript.

https://github.com/roblox-ts/roblox-ts/pull/1546/checks?check_run_id=3238321112#step:6:16

**Comment by nonara** [comment]
This threw me for a second. The require is wrapped in `try ... catch`. Looks like a type import slipped through to import the full const. Should be fixed in v3.2.1

Thanks for letting me know!
