### ISSUE TITLE
Document usage with Jest

### ISSUE THREAD

**Issue by jasonkuhrt** [LeDDGroup/typescript-transform-paths#142]
Currently the best way I know how but happy to simplify:

https://github.com/jasonkuhrt/template-typescript-lib/blob/main/jest.config.ts

**Comment by nonara** [comment]
Thanks for the suggestion! I had a look, and it looks like it may be possible via https://kulshekhar.github.io/ts-jest/docs/getting-started/options/astTransformers

I'll think on this one for a little bit. Since `ts-jest` has a native way of doing this, I generally recommend using their built-in utility. That said, I can see people potentially wanting to use the plugin for the aspects that lie outside of simple path transformation, so I will keep this in mind.

**Comment by jasonkuhrt** [comment]
Interesting, I did not know about https://kulshekhar.github.io/ts-jest/docs/getting-started/options/astTransformers/#public-transformers.

I'll give this a shot and report back.

If this works, I still think a mention in the docs would be worthwhile.

People using this tool will want it working in Jest, and it's just not obvious how to do that. Brief one-liner integration tips here go a long way. If they get out of date, community usually notices and hopefully opens a PR.

**Comment by jasonkuhrt** [comment]
Hmmmm

It seems that it works by default, just like this:

```ts
import type { InitialOptionsTsJest } from 'ts-jest/dist/types'

const config: InitialOptionsTsJest = {
  preset: 'ts-jest',
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
    'jest-watch-select-projects',
    'jest-watch-suspend',
  ],
  globals: {
    'ts-jest': {
      diagnostics: Boolean(process.env.CI),
    },
  },
}

export default config

```

**Comment by nonara** [comment]
Appreciate the update! It occurred to me that it should, but the docs made it seem like they were using babel instead of typescript for compilation.

Glad it works!

**Comment by jasonkuhrt** [comment]
Update

It seems I was wrong, this is what is needed. Maybe I encountered a cache issue on my end, thinking the reduced code worked when actually it was running the previous.

```ts
import type { InitialOptionsTsJest } from 'ts-jest/dist/types'

const config: InitialOptionsTsJest = {
  preset: 'ts-jest',
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
    'jest-watch-select-projects',
    'jest-watch-suspend',
  ],
  globals: {
    'ts-jest': {
      diagnostics: Boolean(process.env.CI),
      astTransformers: {
        before: ['ts-jest/dist/transformers/path-mapping'],
      },
    },
  },
}

export default config

```

**Comment by pz-uc** [comment]
Any update on this one? 🤔 

Or is there any tutorial how I can make `typescript-transform-paths` work with ts-jest? 
tried for quite a while now and don't find any solution 🤔 

Whatever I do ts-jest still can't resolve my modules.

Also `ts-jest` is officially pointing to this repository to use it in their docs -> https://kulshekhar.github.io/ts-jest/docs/getting-started/options/astTransformers/#public-transformers

**Comment by nonara** [comment]
> Also ts-jest is officially pointing to this repository to use it in their docs
Interesting! Didn't know that. 

> is there any tutorial how I can make typescript-transform-paths work with ts-jest?

A few days ago, I had to set a solution up, and I opted to use their AST transformer. It did work. The one problem is it make it so I can't use `require` while debugging, which was a bit annoying. 

Realistically, the best way to make sure it works is to use [ts-patch](https://github.com/ts-patch). When you do, you can simply add the plugin config to a `tsconfig` file for your tests and it will work. This repo's tests actually exemplify how that can work.

All the wrappers and loaders could be avoided if people did, but in effort to broaden support for people who prefer not to add another tool, I'm adding the extras as I'm able. Unfortunately, I've been swamped lately. I do hope to finish this when things slow down in the next major release.

In the mean time, I hope that helps!

**Comment by pz-uc** [comment]
>Interesting! Didn't know that.

Yes, but unfortunately they just link and don't provide any explanation or example, which is really a pity..

>A few days ago, I had to set a solution up, and I opted to use their AST transformer. It did work. The one problem is it make it so I can't use require while debugging, which was a bit annoying.

Would you mind sharing your solution? I don't mind if I currently can't debug, as long as ts-jest is able to resolve the paths properly.

>Realistically, the best way to make sure it works is to use ts-patch. When you do, you can simply add the plugin config to a tsconfig file for your tests and it will work. This repo's tests actually exemplify how that can work.

Do you have a concrete example how `ts-patch` works together with `ts-jest` to resolve the paths? Unfortunately, they also don't have any examples there.

**Comment by nonara** [comment]
@pz-uc I should probably clarify the readme. There is one "official" way of using this library and there are now several alternatives, if you really don't want to use the official route.

Here are the steps:

1. Add `ts-patch` as a dev dependency 
2. Add `prepare` script `ts-patch install -s`
3. Create a `tsconfig.json` for your tests and add the plugin config

It's as simple as that. If your typescript is patched, it will work.

> I think I found a working solution for me leveraging tsconfig-paths

I actually used to recommend using `tsconfig-paths` over this for non-compile options. I got a lot of users saying that they didn't want to. Ultimately, it should be a faster solution than applying transformation for in-memory execution. Unless you absolutely need some of the additional transform features of this library, that's the way to go!

Would you mind sharing how you got it to work with jest?

**Comment by danielpza** [comment]
Closing to keep the backlog clean. If you are still having this issue, please provide a reproduction example using [this link](https://stackblitz.com/github/leddgroup/typescript-transform-paths/tree/master/examples/basic)

We are not planning on adding new features for now, see https://github.com/LeDDGroup/typescript-transform-paths/issues/438. We are happy to review pull requests though. 

Thanks.
