### ISSUE TITLE
Side effect on *.scss files

### ISSUE THREAD

**Issue by alex-polunochev** [LeDDGroup/typescript-transform-paths#147]
Hello! 👋 
Using `typescript-transform-paths` for the first time to provide paths resolution for a shared package that I publish in the npm registry.

This is the extract from project's gulpfile:
```
...
const ts = require('gulp-typescript')

const tsProject = ts.createProject(`${path.join(__dirname, 'tsconfig.json')}`, {
    typescript: require('ttypescript'),
})

const watchPaths = [
    'src/**/*.ts',
    'src/**/*.tsx',
    'src/**/*.d.ts',
    '!src/**/*.test.ts*',
]
gulp.task('shared-package:assets', (cb) => {
    return gulp
        .src(['src/**/*.scss'], {
            cwd: __dirname,
        })
        .pipe(gulp.dest(`${path.join(__dirname, 'lib/')}`))
})

gulp.task('shared-package:build', function (cb) {
    return gulp
        .src(watchPaths, {
            cwd: __dirname,
        })
        .pipe(tsProject())
        .pipe(gulp.dest(`${path.join(__dirname, 'lib/')}`))
})
```

This is the `tsconfig`:
```
{
    "compilerOptions": {
        "baseUrl": "src",
        "outDir": "lib",
        "jsx": "react",
        "lib": ["es6", "dom", "es2017.object", "es2016.array.include"],
        "declaration": true,
        "declarationMap": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "paths": {
            "components/*": ["components/*"],
            ... // more of the same
        },
        "plugins": [
            {
                "transform": "typescript-transform-paths"
            },
            {
                "transform": "typescript-transform-paths",
                "afterDeclarations": true
            }
        ]
    },
    "include": ["./src/**/*"]
}
```

After adding `path` and `plugins` as shown above, I can compile the project and can see the expected changes in the compiled js and ts files locally (e.g. adds `./` or `../../..`), all good. But once the code gets pushed to the pipelines for the monorepo, and the app that uses this shared package gets built with the webpack, the errors start showing up:
```
Error: ModuleNotFoundError: Module not found: Error: Can't resolve './Button.module.scss' in '/builds/hZMJcLfX/1/reponame/packages/shared-package/lib/components/common/Button'
...
[more of the same]
```
All `.scss` modules are reported as not resolved. 

I remove `plugins` from the tsconfig of the shared package, push to pipelines again, and the errors are gone 👀 .

I compared the way the css files imports looked before and after applyingthe plugin, and there's no difference:
```
var Button_module_scss_1 = __importDefault(require("./Button.module.scss"));
```

It's likely a long shot, but wonder if you have any ideas why adding  `plugins` could have such a side-effect.
Thanks!

**Comment by nonara** [comment]
Hi Alex. Sorry to hear you're having issues. That error is generated by Webpack, so I think you'd have more luck there. 

Our plugin doesn't change the way anything gets resolved. It simply alters rewrites the output module specifiers. One suggestion might be that you use plugin config for the initial build step, but then use a separate extended tsconfig for webpack with plugins set to `[]`

I wish you luck with it! If you end up figuring out what's going on, I'd be interested to hear about it.
