### ISSUE TITLE
provided as Transformer Plugin

### ISSUE THREAD

**Issue by zyf0330** [LeDDGroup/typescript-transform-paths#154]
Hello, I use nx which supports to pass transformer to tsc compiler, but it requires plugin is a Transformer Plugin.
This is error `typescript-transform-paths/register is not a Transformer Plugin. It does not provide neither before(), after(), nor afterDeclarations()`.
Does this plugin support it?
Thanks!

**Comment by nonara** [comment]
Hello. I'm not familiar with nx's transformer structure. You could probably write a wrapper pretty easily that provides `before` and `afterDeclarations` exported functions that pass to `transform` in https://github.com/LeDDGroup/typescript-transform-paths/blob/master/src/transformer.ts

If you get one working, I'd be happy to incorporate it into the library.

**Comment by zyf0330** [comment]
@nonara 
This is my PR, but I don't know why it doesn't work. Code executes into `ts.Transformer`, but not into `nodeVisitor` in `visitor.js`.
https://github.com/LeDDGroup/typescript-transform-paths/pull/155

**Comment by nonara** [comment]
Thanks for the effort! You'll want to make sure current tests pass and add tests for working with nx.

I'll have a closer look this weekend.

**Comment by zyf0330** [comment]
@nonara I test again, and it works. Just don't know why. I will add tests.

**Comment by nonara** [comment]
Added in [v3.4.0](https://github.com/LeDDGroup/typescript-transform-paths/releases/tag/v3.4.0). Let me know if you have any issues with it!
