### ISSUE TITLE
[Bug] Incorrect transformer signature in types definition file

### ISSUE THREAD

**Issue by kuoruan** [LeDDGroup/typescript-transform-paths#156]
https://github.com/LeDDGroup/typescript-transform-paths/blob/83349e4e1b84efaa28ee3efbc09c8e15369f4836/types/index.d.ts#L36

I think this should `ts.CustomTransformerFactory`

**Comment by nonara** [comment]
Thank you for the report! You are correct on that. I will get that fixed.
