### ISSUE TITLE
Feature Request: TypeScript 4.8 support.

### ISSUE THREAD

**Issue by rogerleung0411** [LeDDGroup/typescript-transform-paths#161]
After upgrading ts to 4.8+, a deprecation warning log appears, like: `DeprecationWarning: 'updateImportTypeNode' has been deprecated since v4.6.0. Use the overload that accepts 'assertions'`. FYI:
- ts mark `updateImportTypeNode` function without `assertions` argument passed in as deprecated: https://github.com/microsoft/TypeScript/commit/1e65b330a71cc09065b31f1724d78e931aafed51#diff-8b0120099d4b9f42963ae5d72a6e50888150dbe3fd0d3cd43406d4d310ba4077
- ts-expose-externals has dropped support of the elder `updateImportTypeNode` in this commit: https://github.com/nonara/ts-expose-internals/commit/8a2deb7a41c906a50382215fbb228224e5bd2a03, by removing the elder function signature.

May this package internally support both typescript 4.8 above/below, or just upgrade deps and release a version with such a breaking change? I personally have time to send a pr if you are busy, just to discuss how we should do before coding. @nonara

**Comment by nonara** [comment]
Hi @rogerleung0411! Thanks for the report.

There is another open issue that is related. I appreciate the offer to help! I have been slammed lately, but I will addressing this later today. I'll keep you posted.

**Comment by nonara** [comment]
Added in [v3.4.0](https://github.com/LeDDGroup/typescript-transform-paths/releases/tag/v3.4.0)
