### ISSUE TITLE
[Bug] Paths needlessly go back to root on macOS

### ISSUE THREAD

**Issue by nathtumlin-tanium** [LeDDGroup/typescript-transform-paths#167]
macOS has case-insensitive filenames and in resolve-module-name.ts `srcFileOutputDir` has a path starting with `/Users/` and `moduleFileOutputDir` has a path starting with `/users/` [code link](https://github.com/LeDDGroup/typescript-transform-paths/blob/de76b59fc364c5f5e400d87776e0e5a8be7ed65c/src/utils/resolve-module-name.ts#L156-L157). This means that the `path.relative` call ends up `..`ing all the way back up to `/` and creating a path like `require('../../../../../users/nath/foo/src/bar')`.

I did some digging and it looks like in the `SourceFile` objects returned from the compiler API's `getSourceFiles` the `fileName` property has an uppercase `Users` and is constructed by concatting things with `process.cwd()` and things like `path` and `resolvedPath` have the lowercase `users` and I'm not sure where those come from.

Any thoughts on how to fix this either through code changes or a config change? Right now I'm just modifying the `path.relative` call to add some `.toLowerCase()`'s, but that won't work in general.

**Comment by nathtumlin-tanium** [comment]
I have a patch we're using locally that uses `fs.realpathSync.native`, I'll see if I can put it up here

**Comment by nonara** [comment]
@nathtumlin-tanium Ok, great. If you can tell me where you patched it, I can push a fixed version.

**Comment by nathtumlin-tanium** [comment]
I replaced the calls to `path.relative` in [resolve-module-name.ts](https://github.com/LeDDGroup/typescript-transform-paths/blob/master/src/utils/resolve-module-name.ts#L175) with a helper function that updates the from and to parameters with `fs.realpathSync.native(from)` and `fs.realpathSync.native(to)`. Actually I update the values within a `try/catch` so that if the path doesn't exist on disk it doesn't error and just uses what it has.

Sorry, my company is a little strange about contributing code externally but hopefully that's enough to get it, it should be like a < 20 line diff.

**Comment by bradennapier** [comment]
@nathtumlin-tanium can you confirm the PR #171 is inline with your expectations?  It works perfectly for my system but just in case I may have missed an edge case?
