### ISSUE TITLE
What about supporting easy setup CLi command?

### ISSUE THREAD

**Issue by samchon** [LeDDGroup/typescript-transform-paths#172]
As `typescript-transform-paths` is a transformer library, it requires additional configuration on `tsconfig.json` (plugins).

I think it would be much convenient if `typescript-transform-paths` support setup CLI configuring the `tsconfig.json` file automatically. Also, it would be better installing `ttypescript` or `ts-patch` at the same time. Especially, when user selected `ts-patch`, the `package.json` should be configured automatically (`npm run prepare` command), too.

```bash
npx typescript-transform-paths setup
npx typescript-transform-paths setup --compiler ttypescript
npx typescript-transform-paths setup --compiler ts-patch
```

If you're okay, I'll send a PR about it.

You can experience how it works, through below commands:

```bash
npx typia setup
npx typia setup --compiler ts-patch
npx typia setup --manager yarn
npx typia setup --project tsconfig.test.json
```

**Comment by danielpza** [comment]
I think this is better left to a separate project, since the setup steps are not exclusive to typescript-transform-paths

**Comment by nonara** [comment]
Hi @samchon 

I agree with Daniel on this one. We will be releasing a rewrite of ts-patch soon which will have CLI commands that will effectively do what you're looking for.

The new tsp will also use better modification logic and even offer in-memory modification, which will allow users to migrate from ttypescript.
