### ISSUE TITLE
[Feature] Add an option to exclude by keys

### ISSUE THREAD

**Issue by Sylphide** [LeDDGroup/typescript-transform-paths#175]
Hi,

Would it be possible to add an option to exclude resolution by key pattern in addition to the one with resolved path pattern?
I am using an NX monorepo and I would like to transform only the paths of the current library but not the external ones.

For example I have this in my tsconfig.json

```
"paths": {
      "@myorg/database": ["libs/database/src/index.ts"],
      "@myorg/dtos": ["libs/dtos/src/index.ts"],
      "@/database/*": ["libs/database/src/*"],
      "@/dtos/*": ["libs/dtos/src/*"],
}
```

In my database lib I would use `@/database/*` to reference my lib root folder. Those paths I'd like to be transformed. On the contrary, I would reference dtos exported objects with `@myorg/dtos` and I don't want them to be transformed.

Since all libs resides at the same level, dtos would resolve to something like `../../../../dtos`. The only exclude patterns working would have to include dtos only. I think it is not accurate enough and would prevent me from having another dtos folder in my database lib.

Hence my request to have an option that would allow to exclude by tsconfig keys like in my case something like `"excludeKeys": ["@myorg/*"]`

Thanks

**Comment by danielpza** [comment]
Have you tried https://github.com/LeDDGroup/typescript-transform-paths#exclusion-patterns?

**Comment by Sylphide** [comment]
Yes I tried, but I haven't found a pattern matching only external libs resolutions since the resolve at the same level as the current lib.

**Comment by danielpza** [comment]
Can you post what glob patterns you have tried?

**Comment by Sylphide** [comment]
The only patterns working were `"**/dtos/**"` and `"**/dtos"`.

**Comment by nonara** [comment]
Thank you for the suggestion, @Sylphide.

For most cases, exclusion patterns should cover it. From what I understand, however, you want to be able to have a path alias that points to the same file as another path alias, but you'd like to only transform for a specific alias prefix. If that is correct, that would not be covered by exclusion patterns.

At this point, I don't think that's going to be a broad enough use case to warrant adding another config property, but if anyone wants to weigh in in the future, we may reconsider down the line.

In the mean time, I would suggest simply prefixing paths (where you can't use the exclusion pattern) with `@no-transform` tags to ensure they are preserved.
