### ISSUE TITLE
[Documentation] Blog Post Contribution

### ISSUE THREAD

**Issue by oleersoy** [LeDDGroup/typescript-transform-paths#19]
Wrote up a blog post with MVCE example from the last issue showing how to put the plugin to use.  Thanks again for this awesome plugin!

https://medium.com/@ole.ersoy/node-consumable-modules-with-typescript-paths-ed88a5f332fa?postPublishedType=initial

**Comment by danielpza** [comment]
That's great @oleersoy, thanks, I'll add the article to the project readme.

What do you think about showing how would it end after refactoring from relative to absolute paths in the article?

**Comment by danielpza** [comment]
@all-contributors please add @oleersoy for blog
