### ISSUE TITLE
index.js main file does not emit `./` for modules

### ISSUE THREAD

**Issue by roblav96** [LeDDGroup/typescript-transform-paths#2]
Any files emitted at the root of `./dist/*.js` do not include the `./` path at the beginning of modules.

## `tsconfig.json`
```json
{
	"baseUrl": ".",
	"outDir": "dist",
	"target": "es5",
	"paths": {
		"@/*": ["src/*"]
	},
	"plugins": [
		{ "transform": "typescript-transform-paths" },
	]
}
```

## Example:
Currently `./dist/index.js` looks like:
```javascript
var http = require("adapters/http");
```
When it should be:
```javascript
var http = require("./adapters/http");
```

**Comment by roblav96** [comment]
Modifying [index.ts:30](https://github.com/LeDDGroup/typescript-transform-paths/blob/b6d54f70fe6433f1b5d527021b1e142609daad4a/src/index.ts#L30) to add `'./' + ` before relative like so:
```typescript
const file = './' + relative(fileDir, resolve(baseUrl, out));
```
fixes the problem, but I doubt this is the proper solution.

**Comment by danielpa9708** [comment]
Thanks for reporting the issue, I'll look into it

**Comment by danielpa9708** [comment]
> const file = './' + relative(fileDir, resolve(baseUrl, out));

@roblav96 I think it was pretty close with what I came up with, I will merge it tomorrow if you have any thoughts on it.

**Comment by roblav96** [comment]
@danielpza I ended up using [ilearnio/module-alias](https://github.com/ilearnio/module-alias) so I haven't been able to test this.
