### ISSUE TITLE
Imported Types Deleted From Declarations

### ISSUE THREAD

**Issue by travigd** [LeDDGroup/typescript-transform-paths#23]
This is related to #9 (and associated PR #10).

It seems like (for versions > v1.1.0) typescript-transform-paths erases type information from declaration files which is a _problem_ when you're trying to create a library that exposes functions that use that type information. I created a simple repo to show this: https://github.com/travigd/ts-transform-paths-bug-repro

Short version, `index.ts` is
```ts
import {Foo, logFoo} from "@/foo";

export function bar(f: Foo) {
  logFoo(f);
}
```

The resulting `index.d.ts` for recent versions (this is in the `dist-bug` directory in that repo) is 
```ts
export declare function bar(f: Foo): void;
```

For older versions (I specifically install v1.1.0 since it was released before #10), I get this (which is correct for the declarations file):
```ts
import { Foo } from "./foo";
export declare function bar(f: Foo): void;
```

**Comment by danielpza** [comment]
A fix is up in v1.1.5, please upgrade.
