### ISSUE TITLE
Import not generated

### ISSUE THREAD

**Issue by oleersoy** [LeDDGroup/typescript-transform-paths#24]
[`ObjectErrors`](https://github.com/fireflysemantics/validator/blob/master/src/container/error/ObjectErrors.ts) import `ValidationError`.

When the projects build is run, the import is not generated.  I think it's because `ObjectErrors` and `ValidationError` both reside in the same directory.

If I do not use a `paths` import, but instead switch it to a relative import, then the build generates the import.

To see the current behavior:
```
git clone git@github.com:fireflysemantics/validator.git
npm run dist
```

Look at `dist/container/error/ObjectErrors.d.ts`.  It will be missing the `ValidationError` import.

**Comment by oleersoy** [comment]
Found another one.  Inisde the `ValidatorError` the `ValidationContext` import is not being generated:

https://github.com/fireflysemantics/validator/blob/master/src/container/error/ValidationError.ts

**Comment by oleersoy** [comment]
I'm finding more now.  Looks like a lot of imports are not being generated in general.

**Comment by oleersoy** [comment]
Before switching over to this plugin I was using a pretty simple script to perform the path translations:

```
const fs = require("fs");
const globby = require("globby");
const cpy = require("cpy"); 
require("mkdirp").sync("dist");
cpy("package.json", "dist");
cpy("README.md", "dist");
cpy("src/index.ts", "dist");
const options = { overwrite: true };
const rc = require("recursive-copy");
rc("target/src/", "dist", options).then(() => {
  globby("./dist/**/*.js")
    .then(paths => {
      paths.forEach(update);
    })
    .catch(e => console.log(e));

    globby("./dist/**/*.d.ts")
    .then(paths => {
      paths.forEach(update);
    })
    .catch(e => console.log(e));   
});

function update(path) {
  count = (path.match(/\//g) || []).length;
  let replacement = "";
  if (count == 2) {
    replacement = "./";
  } else if (count > 2) {
    const size = count - 2;
    replacement = Array(size)
      .fill("../")
      .join("");
  } else {
    throw new Error("Invalid / count in path of file");
  }
  let js = fs.readFileSync(path, "utf8");
  js = js.replace(/@fs\//g, replacement);
  fs.writeFileSync(path, js);
}
```

I worked perfectly.  Perhaps the algorithm could be incorporated here.

**Comment by oleersoy** [comment]
I'm going to change the paths that are not being generated back to relative paths.  This is the commit ID for the build that has the errors:

https://github.com/fireflysemantics/validator/commit/24e5eee4e43c67c53174dab9bc7a798ae1b0a789

It's corresponds to package version 1.18.  The new release will have version 1.19.

**Comment by oleersoy** [comment]
I noticed that for these imports:

```
import { ValidationContext } from "./";
import { getPropertyKey } from "../../utilities/utilities";
import { isDefined } from "@fireflysemantics/is";
import { MetaClass } from "@fs/container/validation";
```

The imports `IsDefined` and `MetaClass` are not imported.  That's OK because they are not part of the `.d.ts` type information.  So I wonder if the plugin is confused WRT which nodes are part of the `.d.ts` type information and which ones are not.

**Comment by danielpza** [comment]
A fix is up with v1.1.5, please upgrade. It should also fix #23 and #22.

**Comment by oleersoy** [comment]
Awesome - Will try it out ASAP!!  THANKS!!

**Comment by oleersoy** [comment]
OK - Hopefully just one weird bug left.  In `src/container/validation/index.ts` I have the following exports:
```
export { MetaClass } from "@fs/container/validation/MetaClass";
export { ValidationContainer } from "@fs/container/validation/ValidationContainer";
export { ValidationContext } from "@fs/container/validation/ValidationContext";
export { ValidationOptions } from "@fs/container/validation/ValidationOptions";
```

When the build runs the corresponding `index.d.ts` file has these exports:

```
export { MetaClass } from "./MetaClass";
export { ValidationContainer } from "./ValidationContainer";
export { ValidationContext } from "./ValidationContext";
```
So it left off the 
```
export { ValidationOptions } from "@fs/container/validation/ValidationOptions";
```
Export.  Thouhts?

**Comment by danielpza** [comment]
I added a regression test and a fix in https://github.com/LeDDGroup/typescript-transform-paths/commit/0263f06, could you test it and see if there's any other issues before deploying a new version?, is fine either way

**Comment by oleersoy** [comment]
Sure - I'm cloning it right now.

**Comment by oleersoy** [comment]
I just tested it with the cloned install, and it looks like the `ValidationOptions` export is still missing.

**Comment by oleersoy** [comment]
Actually - Hold on - I think maybe the install of the clone did not go right.  Looking at it now.

**Comment by danielpza** [comment]
uhmm, I tested it on your project and it seems to be working, I installed my version from github:

```diff
   "dependencies": {
     "@fireflysemantics/is": "^1.8.21",
     "@types/validator": "^10.11.1",
+    "typescript-transform-paths": "git+https://github.com/LeDDGroup/typescript-transform-paths.git",
     "validator": "^11.0.0"
   }
```

And it shows:

```typescript
export { MetaClass } from "./MetaClass";
export { ValidationContainer } from "./ValidationContainer";
export { ValidationContext } from "./ValidationContext";
export { ValidationOptions } from "./ValidationOptions";
```

**Comment by danielpza** [comment]
nvm, cool, if you find any other issue let me know. Thanks a lot for the feedback

**Comment by oleersoy** [comment]
OK - Just tested it - And it's looking good!  Thanks again!  You rock!

**Comment by danielpza** [comment]
v1.1.6 is up
