### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by oleersoy** [LeDDGroup/typescript-transform-paths#25]
Bumping into a strange issue with Travis.  It says it can't download package.json for typescript transform paths.  It works fine for me locally.  This is the build page:

https://travis-ci.org/fireflysemantics/validator

```
25.56s$ npm ci 
npm ERR! path /home/travis/build/fireflysemantics/validator/node_modules/typescript-transform-paths/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/travis/build/fireflysemantics/validator/node_modules/typescript-transform-paths/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

```

**Comment by danielpza** [comment]
The problem is in https://github.com/fireflysemantics/validator/blob/master/package.json#L48:

```
"typescript-transform-paths": "file:../typescript-transform-paths"
```

I guess you forgot to reference `typescript-transform-paths` back to npm after you were done testing ;)

**Comment by oleersoy** [comment]
Ooooh - Thanks!  I'll get that fixed.
