### ISSUE TITLE
recent minimatch update to 10 causes a node 20 dependency

### ISSUE THREAD

**Issue by spdaley** [LeDDGroup/typescript-transform-paths#271]
The recent minimatch update done https://github.com/LeDDGroup/typescript-transform-paths/pull/244 has added a node 20 dependency to this module. I'm not sure if that's intentional or accidental so submitting this just in case.

I don't see a published supported node version so maybe this is ok and my project can just deal with it but figured I'd submit this to be sure.

Thanks.

**Comment by danielpza** [comment]
Hey, thanks for reaching out.

I think we don't have a set minimum supported node version but I figure we want to support the current node LTS versions, that would include node 18.

I think it's ok to downgrade minimatch, it would be great if you'd be willing to open a PR :)

**Comment by spdaley** [comment]
I'll git it a shot.

**Comment by spdaley** [comment]
https://github.com/LeDDGroup/typescript-transform-paths/pull/272

I can't seem to run `yarn test` so not sure if there is anything wrong but I couldn't do that in the original repo either.

**Comment by danielpza** [comment]
Fixed in 3.5.1. Thanks for contributing @spdaley :heart:
