### ISSUE TITLE
Emits '../' for node_modules and subfolder tsconfig

### ISSUE THREAD

**Issue by viT-1** [LeDDGroup/typescript-transform-paths#31]
tsconfig.base.json compilerOptions:
```
"paths": {
"vue": ["https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"]
}
```

subfolder/tsconfig.json:
```
"extends": "../tsconfig.base.json",
"compilerOptions": {
"baseUrl": ".",
"plugins": [{ "transform": "typescript-transform-paths" }]
}
```

ttsc generated module file:
`import Vue from "../https:/cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js";`

**Comment by danielpza** [comment]
Just to be clear, the expected output is `import Vue from "https:/cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js";` ?

**Comment by viT-1** [comment]
Yes. And I have so much '../' in my module with import from 'vue' as depth of its folder.

**Comment by danielpza** [comment]
@viT-1 , a fix has been released, please upgrade to *v1.1.9*

**Comment by viT-1** [comment]
Thank you!

**Comment by viT-1** [comment]
It seems that is not transformed vue to uri at all.

**Comment by danielpza** [comment]
I'm glad it helps :), feel free to report any issues you might find

**Comment by danielpza** [comment]
@all-contributors please add @viT-1 for bug.

**Comment by viT-1** [comment]
May be this functionality configured as parameter 'imports', using separate file importmap.json?
For example:
tsconfig.son
```
"compilerOptions": {
"module": "es6",
"target": "esnext",
"outDir": "../dist",
"plugins": [{ "transform": "typescript-transform-paths", "imports": "./importmap.json" }] // make relative imports
}
```

importmap.json
```
{
	"importss": {
		"debounce-decorator-ts": [
			"https://cdn.jsdelivr.net/npm/debounce-decorator-ts@1.0.4/dist/debounce-decorator-ts.es5.js"],
		"direct-vuex": [ "/direct-vuex.esm.min.js" ],
		"vue": [ "https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.esm.browser.js" ],
		"vuex": [ "https://cdn.jsdelivr.net/npm/vuex@3.6.2/dist/vuex.esm.browser.min.js" ],
		"vue-class-component": [ "/vue-class-component.js" ],
		"vue-property-decorator": [ "/vue-property-decorator.js" ]
	}
}
```

**Comment by viT-1** [comment]
Related [project](https://github.com/WICG/import-maps)

**Comment by nonara** [comment]
@viT-1 Thanks for the suggestion! I believe that functionality goes a bit beyond the scope of what we're doing, however.

Our aim with this plugin is to rewrite imports using the `tsconfig.json` `paths` configuration. We rely on the TS compiler API to hand off that resolution to the typescript compiler to ensure that we're in sync.

We have gone a little beyond that directive by providing for single comment resolution overrides, but a change like you're suggesting would require rewriting or splitting the resolution engine, which would come with many side effects. It would also potentially get confusing if there are intersecting resolution paths between `tsconfig` and `importmap`, etc. 

If there is a broad enough interest in adding support in the future, we can revisit this, but for now, I think we'll stick with our current path.

You're welcome to fork the repository and use it as a basis that suits your needs, however!

**Comment by viT-1** [comment]
@nonara I agree. I've found [transformer](https://github.com/Jack-Works/ttypescript-browser-like-import-transformer/issues/30) with functionality of interest.
