### ISSUE TITLE
why local path is not transformed?

### ISSUE THREAD

**Issue by viT-1** [LeDDGroup/typescript-transform-paths#34]
I have [success](https://github.com/LeDDGroup/typescript-transform-paths/issues/31) with tsconfig.json paths:
`"vue": ["https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.esm.browser.js"]`
path is transformed to import from 'url...'
but if I use (for fixing vue-class-component.esm.js `import vue from 'vue'` to `import vue from 'url...'` resolving es6 modules without importmap)
`"vue-class-component": ["../dist/vue-class-component.esm.js"],`
nothing happens with import from 'vue-class-component'

**Comment by viT-1** [comment]
Instead of [this](https://github.com/viT-1/systemjs-ts-es6-vue/blob/53f31f47975de22f74a60468d529a9065dd46605/gulpfile.esm.js#L75) I want to use transform path in [tsconfig](https://github.com/viT-1/systemjs-ts-es6-vue/blob/53f31f47975de22f74a60468d529a9065dd46605/src/tsconfig.dev.json#L12) (vue use cdn, vue-class-component needs something like `"vue-class-component": ["../dist/vue-class-component.esm.js"]`)

**Comment by danielpza** [comment]
@viT-1 , I'm not sure what's the expected output here, can you post snippets of your tsconfig.json, and the output and desired behavior?

**Comment by viT-1** [comment]
https://github.com/viT-1/systemjs-ts-es6-vue/commit/77c91bc4ac94088e43802602280768802dce6e79
npm run deploy.dev should transpile dist\common.blocks\IamHeader\IamHeader.js
with import Component from '[relative path to dist/vue-class-component.esm.js]';
but I have `import Component from 'vue-class-component';`

**Comment by danielpza** [comment]
@viT-1, since v1.1.10 (See https://github.com/LeDDGroup/typescript-transform-paths/issues/30 and https://github.com/LeDDGroup/typescript-transform-paths/commit/e6c51e0bfb8b7f72bc72be7919f2fe1f284732dc)  the plugins no longer uses the first entry in path for resolution, instead it check for one entry that exists and falls back to the original, so in this case is failing because `../dist/vue-class-component.esm.js` didn't exist at compilation time.  One workaround would be to generate the file first:

```diff
modified   package.json
@@ -23,7 +23,7 @@
         "postdeploy": "npm run wwwdeploy",
         "predeploy.dev": "npm run clean",
         "deploy.dev": "ttsc --project ./src/tsconfig.dev.json",
-        "postdeploy.dev": "gulp postdeploy.dev && npm run wwwdeploy",
+        "predeploy.dev": "gulp postdeploy.dev && npm run wwwdeploy",
         "lint": "eslint **/*.{ts,json,js} *.*",
         "clean.node": "rm -rf ./distnode",
         "predeploy.node": "npm run clean.node",
```

However I'm open to discussion for a more consistent fix, maybe we could enable an option to always use the entries in path even if it doesn't exist at compilation time. Any ideas ?

/cc @richardspence

**Comment by viT-1** [comment]
[Changed to predeploy](https://github.com/viT-1/systemjs-ts-es6-vue/commit/6ada3e43b466c0a48046a2e92a290d8f45eaff52) but it caused to another bug (may be ttypescript issue): in dist now I have another dist and src =(
Strange effect after typescript-transform-paths. If I [remove relative path](https://github.com/viT-1/systemjs-ts-es6-vue/blob/6ada3e43b466c0a48046a2e92a290d8f45eaff52/src/tsconfig.dev.json#L12) 'dist' directory structure becomes as expected (without dist/dist and dist/src).

**Comment by danielpza** [comment]
Closing to keep the repository clean, if you have any more problems or ideas feel free to open an issue.

**Comment by viT-1** [comment]
>  instead it check for one entry that exists and falls back to the original
@danielpza can it be configured? e.g. with npm warning, but force transform to local or relative url paths from tsconfig?

**Comment by nonara** [comment]
@viT-1 If you're still interested in this. please try with v2 and see if it does what you'd like. If it doesn't do what you expect, please give me a little more detail.

We've recently transitioned to relying fully on the TS Compiler API, so we likely won't be implementing any logic which diverges from the standard behaviour, but if I'm open to hearing your use case!

**Comment by nonara** [comment]
Closing for housekeeping. If there is any further issue, feel free to comment, and we can investigate.

**Comment by viT-1** [comment]
@nonara  No, v2 not helped me to have correct resolved modules.
After using new version of plugin I had to [correct paths manually](https://github.com/viT-1/systemjs-ts-es6/commit/6f3beb0f747b0c6b4399a209effa11c4697460c9) from index/index.js to index.js

After changing my gulp code I need to [set extensions still](https://github.com/viT-1/systemjs-ts-es6/commit/c2a2e57ca746798c76405ff57f5ce13f26f7cdd3).
I don't want to use Babel or such transpiler because of tsc or ttsc it is already transpiler for *.ts files.

**Comment by viT-1** [comment]
Extensions of js files it is not typescript-transform-paths issue, ok.
