### ISSUE TITLE
Path to files with multiple `.` extensions not transformed 

### ISSUE THREAD

**Issue by laij84** [LeDDGroup/typescript-transform-paths#36]
I have a monorepo setup with a package that contains React Native components. The naming convention for React Native files is to have `.native` in the extension, for example `utils.native.ts`. 

Import paths referring to files with multiple `.` extensions do not get transformed into relative paths.

**Comment by danielpza** [comment]
@laij84 thanks for the bug report , you can check #37 for the fix, it should be published in short.

/cc @all-contributors

**Comment by danielpza** [comment]
@all-contributors add @laij84 for bug
