### ISSUE TITLE
Seems to be not working with dynamic import expression

### ISSUE THREAD

**Issue by hedwiggggg** [LeDDGroup/typescript-transform-paths#45]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html

Hey, i'm using the dynamic import if i'm only importing a type, to prevent import cycles.
But it seems, that these import aliases won't get transformed.

`declare type QuestionModel = import('@/models/Question/model').QuestionModel;`

Just stays the same, the other, es6-style imports are transformed just fine.

**Comment by hedwiggggg** [comment]
I've searched a bit and found the typescript method:

`isImportTypeNode`

the function call is true for dynamic imports. 
We could use that to unpath the dynamic imports.

**Comment by danielpza** [comment]
@hedwiggggg thanks for the bug report. It would be great if you make a PR, it seems you are on the right track. Otherwise I'll address it later when I'm available.

**Comment by hedwiggggg** [comment]
@danielpza See the PR, that should do the trick.

**Comment by danielpza** [comment]
fixed in v1.1.14
