### ISSUE TITLE
external modules with the same name as directories

### ISSUE THREAD

**Issue by leviwheatcroft** [LeDDGroup/typescript-transform-paths#49]
Probably more of a limitation than a bug really...

If you have a directory in your project with the same name as an external module, typescript-transform-paths will replace the import for the external module with a relative path to the directory, instead of importing the external module.

For example, if you have a file `graphql/types/scalar.ts` which includes something like `import { GraphQLScalarType } from 'graphql'`, the import will be transpiled to `const GraphQLScalarType = require("..")`.

I guess you could check whether there's a package with the same name as the import before converting the path.

**Comment by danielpza** [comment]
:thinking: well, we'd have to check with the typescript module resolution strategy https://www.typescriptlang.org/docs/handbook/module-resolution.html.

Could you rerun typescript with the `--traceResolution` flag as stated here https://www.typescriptlang.org/docs/handbook/module-resolution.html#tracing-module-resolution.
