### ISSUE TITLE
Run on Window produce Window path (backslash) instead of Posix path.

### ISSUE THREAD

**Issue by joshuaavalon** [LeDDGroup/typescript-transform-paths#5]
Running this plugin on Window produce paths like `..\\..\\utils` instead of `../../utils`.

This is because node use environment specific path.

https://github.com/LeDDGroup/typescript-transform-paths/blob/de7d3d8696cf099d8a8f2b19ab69df0f32105118/src/index.ts#L2

I recommend using something like [slash](https://www.npmjs.com/package/slash) to convert the path to posix path.

https://github.com/LeDDGroup/typescript-transform-paths/blob/de7d3d8696cf099d8a8f2b19ab69df0f32105118/src/index.ts#L28

**Comment by danielpa9708** [comment]
Thanks for the bug report, I'll check it out, I think path have a `normalize` function that fix this issue
