### ISSUE TITLE
Compiled JS file has a require that points to incorrect TS file extension

### ISSUE THREAD

**Issue by george43g** [LeDDGroup/typescript-transform-paths#59]
I noticed a bug with my setup.

I use ttsc to compile a TS library to a JS one.

There are `paths` in my `tsconfig.json` that point to specific `*.ts` files.
For example: `"@my-app/lib1": "./path/to/index.ts"`
The transformer changes these to `require('.../path/to/index.ts')` - the file extension remains the same in the compiled version, even though `tsc` would normally convert these to `.js` or no extension at all.

**Comment by danielpza** [comment]
should be fixed by #61
