### ISSUE TITLE
If the file extension is `js` then it should be kept

### ISSUE THREAD

**Issue by hungtcs** [LeDDGroup/typescript-transform-paths#89]
### Reason
This will break the compatibility of esmodule, and inconsistent with `tsc`

### Version
- typescript: 4.1.3
- typescript-transform-paths: 2.2.0

### Steps to reproduce
There are 4 files in total：
```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ES2020",
    "outDir": "./dist/",
    "strict": true,
    "baseUrl": "./",
    "paths": {
      "@shared/*": [
        "src/shared/*"
      ]
    },
    "esModuleInterop": true,
    "plugins": [
      // {
      //   "transform": "typescript-transform-paths"
      // }
    ],
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```
```ts
// src/index.ts
import { value } from './value.js';   // <-- './value.js' is not an error
console.log(value);
```
```ts
// src/value.ts
export const value = 12;
```
```html
<!-- index.html -->
<body>
  <script src="dist/index.js" type="module"></script>
</body>
```

##### The output js without `typescript-transform-paths`
![image](https://user-images.githubusercontent.com/11692935/103671192-8b51c980-4fb5-11eb-9ef1-999324744cd8.png)

##### The output js with `typescript-transform-paths`
![image](https://user-images.githubusercontent.com/11692935/103671268-a45a7a80-4fb5-11eb-8a75-33e8300525c7.png)

This causes the browser to fail to fetch the file:
![image](https://user-images.githubusercontent.com/11692935/103671337-bc31fe80-4fb5-11eb-9aa1-08291e54c891.png)

**Comment by nonara** [comment]
Thanks for the report.

Seems that the best solution here would be to preserve extension if it's explicitly added in the original source. I'll try to get a fix out shortly.

**Comment by nonara** [comment]
Sorted in v2.2.1

**Comment by hungtcs** [comment]
The following are my test results.

### Version
- typescript: 4.1.3
- typescript-transform-paths: 2.2.1

### Steps to reproduce
```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ES2020",
    "outDir": "./dist/",
    "strict": true,
    "baseUrl": "./",
    "paths": {
      "@shared/*": [
        "src/shared/*"
      ]
    },
    "esModuleInterop": true,
    "plugins": [
      {
        "transform": "typescript-transform-paths"
      }
    ],
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

```typescript
// src/index.ts
import { value } from './value.js';
import { b } from '@shared/index.js';

console.log({ value, b });
```

```typescript
// src/value.ts
export const value: number = 1;
```

```typescript
// src/shared/index.ts
export const b: string = 'shared string';
```

Next is js codes from tsc and ttsc respectively:

```js
// tsc without typescript-transform-paths
import { value } from './value.js';
import { b } from '@shared/index.js';
console.log({ value, b });
```

```js
// ttsc with typescript-transform-paths
import { value } from "./value";
import { b } from "./shared/index";
console.log({ value, b });
```

------------------

Commit 15feb70 only working without paths config
```jsonc
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ES2020",
    "outDir": "./dist/",
    "strict": true,
    "baseUrl": "./",
    // "paths": {
    //   "@shared/*": [
    //     "src/shared/*"
    //   ]
    // },
    "esModuleInterop": true,
    "plugins": [
      {
        "transform": "typescript-transform-paths"
      }
    ],
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

thanks.

**Comment by nonara** [comment]
Good catch. Looks like I forgot to account for interchangeability between js/ts extensions. I should have read the issue more carefully! 😄 

I corrected and narrowed the logic to apply to explicit `.js` and `.jsx` extensions. I believe that this should be broad enough. The only other possible related issue is that it will still strip an explicit `.json` extension, but I don't think that would break anything with regard to esmodules. Feel free to correct me if I'm wrong!

In any case, v2.2.2 should work for you. Let me know if you have any issues.

**Comment by hungtcs** [comment]
@nonara Thank you for the quick resolution, [v2.2.2](https://github.com/LeDDGroup/typescript-transform-paths/releases/tag/v2.2.2) passed my test case perfectly.
