### ISSUE TITLE
Type only import not deleted from result file

### ISSUE THREAD

**Issue by anion155** [LeDDGroup/typescript-transform-paths#9]
Import of types error (cyclic import is imported, cause it does breaks functionality):

```typescript
// a.js
import { B } from '@/b';
import { NotRuntime } from '@/c';

export class A {
    constructor(public name: NotRuntime) {}
}

export const b = new B();
b.print(new A('This is a random name'));

// b.ts
import { A } from '@/a';

export class B {
    print(a: A) {
        console.log(a.name);
    }
}

// c.ts
export type NotRuntime = string;
throw new Error('Should never happen, until `import "@/c"`');
```

Produces invalid code with circular dependencies. When without paths and this plugin, resulting b.js does not content `require('./a.js')`, which resolves circular dependency error.

**Comment by anion155** [comment]
https://github.com/microsoft/TypeScript/issues/31446

**Comment by anion155** [comment]
@danielpza What if `node.moduleSpecifier.text = file;` instead update? This is fixing issue for import clause at least.

**Comment by danielpza** [comment]
If that fixes the problem is fine by me. I'll check the test to make sure everything is fine and deploy a new release.

**Comment by anion155** [comment]
@danielpza It does looks like ts bug, or maybe we have to update some modules cache. I have created thread on ts, will see what ts guru say about this. Meanwhile  I'll be looking to this further.
