### ISSUE TITLE
Typings fails during "afterDeclarations" transform

### ISSUE THREAD

**Issue by ksnyde** [LeDDGroup/typescript-transform-paths#90]
I have code which compiles without issue using `tsc` and used to work fine with `ttsc` and in Rollup with the `ttypscript` replacement and using the "typescript-transform-paths" plugin.

For context, my `tsconfig.json` file is:

```json
{
  "compilerOptions": {
    "declaration": false,
    "module": "esnext",
    "target": "es2018",
    "lib": ["es2015.reflect", "DOM"],
    "moduleResolution": "node",
    "sourceMap": true,
    "noImplicitAny": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noEmit": true,
    "removeComments": false,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    },
    "plugins": [
      { "transform": "typescript-transform-paths" },
      { "transform": "typescript-transform-paths", "afterDeclarations": true }
    ]
  },

  "include": ["src"]
}
```

This same repo and **tsconfig** used to compile but after updating a number of requirements (including Typescript to 4.1.3) it now fails with:

```sh
Error: Debug Failure. False expression: Node must have a real position for this operation
    at NodeObject.assertHasRealPosition (/Volumes/Coding/forest-fire/vuex-plugin-firemodel/node_modules/typescript/lib/typescript.js:146074:22)
    at NodeObject.getFullText (/Volumes/Coding/forest-fire/vuex-plugin-firemodel/node_modules/typescript/lib/typescript.js:146104:18)
    at getStatementTags (/Volumes/Coding/forest-fire/vuex-plugin-firemodel/node_modules/typescript-transform-paths/dist/utils/resolve-path-update-node.js:96:35)
    at Object.resolvePathAndUpdateNode (/Volumes/Coding/forest-fire/vuex-plugin-firemodel/node_modules/typescript-transform-paths/dist/utils/resolve-path-update-node.js:17:18)
    at Object.nodeVisitor (/Volumes/Coding/forest-fire/vuex-plugin-firemodel/node_modules/typescript-transform-paths/dist/visitor.js:76:24)
    at visitNodes (/Volumes/Coding/forest-fire/vuex-plugin-firemodel/node_modules/typescript/lib/typescript.js:80382:48)
```

I have gone into Typescript's code and added code to pull out more information as I was completely confused by the message. When I hit an error condition, I now get a dump of the node's context which looks like this:

```ts
NodeObject {
  pos: -1,
  end: -1,
  flags: 8,
  modifierFlagsCache: 0,
  transformFlags: 1,
  parent: undefined,
  kind: 195,
  argument: NodeObject {
    pos: -1,
    end: -1,
    flags: 8,
    modifierFlagsCache: 0,
    transformFlags: 1,
    parent: undefined,
    kind: 191,
    literal: TokenObject {
      pos: -1,
      end: -1,
      flags: 8,
      modifierFlagsCache: 0,
      transformFlags: 0,
      parent: undefined,
      kind: 10,
      text: '@firebase/auth-types',
      singleQuote: undefined,
      hasExtendedUnicodeEscape: undefined
    }
  },
  qualifier: IdentifierObject {
    pos: -1,
    end: -1,
    flags: 8,
    modifierFlagsCache: 0,
    transformFlags: 0,
    parent: undefined,
    kind: 78,
    originalKeywordKind: undefined,
    escapedText: 'FirebaseAuth',
    emitNode: { flags: 16777216 },
    symbol: SymbolObject {
      flags: 32,
      escapedName: 'FirebaseAuth',
      declarations: [Array],
      exports: [Map],
      members: [Map],
      valueDeclaration: [NodeObject],
      parent: [SymbolObject],
      id: 24262,
      isReferenced: 788968
    },
    typeArguments: undefined
  },
  typeArguments: undefined,
  isTypeOf: false,
  jsDocCache: []
}
```

With my someone low resolution understanding this seems to suggest it's taking some issue with the `FirebaseAuth` symbol which is being imported from a package that does indeed export the given symbol but considering this repo hasn't changed at all i'm surprised its not working. Further, if I go into the assertion in Typescript's `NodeObject.assertHasRealPosition` and just remove the assertion, it goes back to transpiling successfully.

**Comment by ksnyde** [comment]
Though somewhat redundant, let me restate what my plugin/transform logic has been to get things to work:

## Previously
```json
"plugins": [
      { "transform": "typescript-transform-paths" }
      { "transform": "typescript-transform-paths", "afterDeclarations": true }
    ]
```

If I adjust and take out the `afterDeclaration`:

## Adjusted
```json
"plugins": [
      { "transform": "typescript-transform-paths" }
    ]
```

It successfully transpiles but does not transform the path aliases in the _types_ which makes it close to useless.

**Comment by ksnyde** [comment]
This project is open source and this experience can be easily reproduced by cloning: https://github.com/forest-fire/vuex-plugin-firemodel and using the @develop branch.

Build command is `yarn build` for the Rollup build process and `yarn build:tsc` for the **ttsc** build.

**Comment by nonara** [comment]
Thanks for the report. Can you please share what version of the plugin you're using?

**Comment by nonara** [comment]
Sorted in v2.2.1

**Comment by ksnyde** [comment]
yay!

**Comment by jacobbogers** [comment]
I am using 2.2.3 and i have he EXACT same issue as @ksnyde did previously

**Comment by jacobbogers** [comment]
I reverted back to v2.2.1 , and it is now working for me, v2.2.3 has this bug again

**Comment by ksnyde** [comment]
Sad to hear this has regressed. I really need this to work so I can alias the hell out of my source code with reckless abandon.

**Comment by nonara** [comment]
@jacobbogers Please paste the full error message and stack.

It isn't possible to be getting the exact same error, as the portion of code in @ksnyde's stack is wrapped with `try .. catch` now. Beyond that, there isn't a code regression.

However, I am seeing that typescript 4.2.x is failing tests, indicating that they may have changed some logic, possibly to do with resolution. I'm looking into it.

In the mean time, please give me your exact error message in the new report you opened, and if you can provide a simple reproduction, it will help expedite

**Comment by nonara** [comment]
@ksnyde Can you confirm that this isn't working for you with v2.2.3?

**Comment by jacobbogers** [comment]
@nanora Hi, I provided steps in https://github.com/LeDDGroup/typescript-transform-paths/issues/97  to fully reproduce this issue, 
I am not getting error messages at all, it is just the emitted files that contain non-translated path aliases

**Comment by ksnyde** [comment]
@nonara I can give it a try ... give me a moment.

**Comment by ksnyde** [comment]
For me ... all paths lead to success. @jacobbogers can you try re-diagnosing?

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/980757/111836975-6b435e00-88b4-11eb-83e4-3dd307f7d36d.png">

**Comment by jacobbogers** [comment]
@ksnyde I provided full steps in detail with output, (including a repo where it all is prepared, and configured)
https://github.com/LeDDGroup/typescript-transform-paths/issues/97
It only takes one command to build, (after you can verify I am using the correct versions, (I also posted snippets from package.json and tsconfig)
Could you please use the example I provided to reproduce? thanks

**Comment by jacobbogers** [comment]
Lets continue conversation under https://github.com/LeDDGroup/typescript-transform-paths/issues/97

**Comment by nonara** [comment]
@ksnyde Thanks for confirming!
