### ISSUE TITLE
v2.2.3 fails to rewrite alias path in decleration file, reverted back to v2.2.1

### ISSUE THREAD

**Issue by jacobbogers** [LeDDGroup/typescript-transform-paths#97]
snippet from tsconfig.json file
```json
 { "transform": "typescript-transform-paths", "afterDeclarations": true }
```

replacing path aliases in decleration files does not work in (current) version 2.2.3 (i reverted back to 2.2.1 and it works with this version)

**Comment by jacobbogers** [comment]
Oh in v 2.2.1 ... these 2 things are mutually exclusive, you cannot emit BOTH js and d.ts files with "transpile" paths aliases
- Either you transpile paths in in emitted js files ` { "transform": "typescript-transform-paths" }` OR you transpile path aliases in *.d.ts files ` { "transform": "typescript-transform-paths", "afterDeclarations": true }`  

but not both at the same time

**Comment by nonara** [comment]
Thanks for reporting the issue, Jacob!

Unfortunately, I'm not able to reproduce this. I have no issue emitting both, and we have fairly comprehensive testing which covers that scenario as well as others. I've also looked at the difference between the versions, and I'm not seeing anything which could cause the sort of difference you've mentioned between the two versions.

I'm going to need a reproduction so I can dig into it further.

**Comment by jacobbogers** [comment]
@nonara, let me create an example

**Comment by jacobbogers** [comment]
Hi,
I am using the master branch (as of this writing) of https://github.com/jacobbogers/libRmath.js

## Here are the steps for reproduction

Here is a reproduction, first let me show you the version numbers:

from `package.json`:

```json
      "typescript-transform-paths": "^2.2.3"
```

from `node_modules/typescript-transform-path/package.json`

```json
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "typescript-transform-paths@2.2.3",
    "name": "typescript-transform-paths",
    .
    .
``` 

tsconfig.json 
```json
 "plugins": [
     .
      {
        "transform": "typescript-transform-paths",
        "afterDeclarations": true
      }
     .
    ],
```

I am using the `tsconfig-commonjs.json` which extends the `tsconfig.json`

Now run:

```bash
npx ttsc -p tsconfig-commonjs.json
```

the `commonjs` directory will have source and typings (in different dirs)

Lets look at the top of the `js` file `commonjs\lib\distributions\cauchy.js`

**Path alias '@common/logger' is NOT translated**

```
const debug_1 = require("debug");
const logger_1 = require("@common/logger");   // <--- NOT TRANSLATED!!
const { isNaN: ISNAN } = Number;
const { PI: M_PI, log } = Math;
const printer = debug_1.debug('dcauchy');

```

Lets look at a typings file `commonjs\types\lib\distributions\cauchy\index.d.ts`

**Path alias '@rng/normal/normal-rng' is translated**

```typescript
export { dcauchy } from "./dcauchy";
export { pcauchy } from "./pcauchy";
export { qcauchy } from "./qcauchy";
import type { IRNGNormal } from "../../rng/normal/normal-rng";  // <--- TRANSLATED
export declare function rcauchy(n: number, location?: number, scale?: number, rng?: IRNGNormal): Float32Array;
//# sourceMappingURL=index.d.ts.map

```

**Comment by jacobbogers** [comment]
Was my previous post in any way helpfull?
Cheers

**Comment by nonara** [comment]
GH didn't send me an email on this, so I didn't see it until now.

It looks to me like you're not added both lines to the config file. If you want to translate for _both_ js and types, you need two entries in plugins. A little annoying, but that's how ttypescript is built.

ie:

```json
    "plugins": [
      { "transform": "typescript-transform-paths" },
      { "transform": "typescript-transform-paths", "afterDeclarations": true }
    ]
```

If that's not the problem, please paste your full tsconfig file.

**Comment by jacobbogers** [comment]
@nanora, superthanks, it works now, with the added line,
I thought that `{ "transform": "typescript-transform-paths", "afterDeclarations": true }` was a superset of the first line (because of the extra `afterDeclerations`)  Thanks for explaining to me about the seperate transform cycles. 

Super

**Comment by nonara** [comment]
No problem. Glad it's working for you! Take care.
